# Generated by Django 5.2.5 on 2025-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Thesis', 'verbose_name_plural': 'Theses'},
        ),
        migrations.AddField(
            model_name='thesis',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='theses_pdf/', verbose_name='Thesis PDF File'),
        ),
    ]
