# Generated by Django 5.2.5 on 2025-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_alter_thesis_options_thesis_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
