# Generated by Django 5.2.7 on 2025-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_thesis_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='ss_paper_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
